USE STARGATE_ANALYTICS;
GO

-- Limpeza para reconstrução de alta fidelidade
IF OBJECT_ID('BLOOMBERG_MASTER_REPORT', 'U') IS NOT NULL DROP TABLE BLOOMBERG_MASTER_REPORT;
GO

CREATE TABLE BLOOMBERG_MASTER_REPORT (
    PERIOD VARCHAR(12),
    BANK_ENTITY VARCHAR(30),
    PROJECTED_REVENUE_USD MONEY,
    CUMULATIVE_AUM_USD MONEY,
    CONFIDENCE_MATRIX VARCHAR(15),
    MISSION_STATUS VARCHAR(20)
);
GO

-- Injeção da Telemetria v15.5 (Scaling 1.26x)
INSERT INTO BLOOMBERG_MASTER_REPORT 
VALUES 
('OCT-2026', 'CITIGROUP INC', 3092817.06, 1310765081.96, 'HIGH', 'SUCCESS'),
('APR-2027', 'GOLDMAN SACHS', 3590920.72, 1391403547.21, 'HIGH', 'SUCCESS'),
('OCT-2027', 'JPMORGAN CHASE', 4169244.86, 1477002902.98, 'STABLE', 'SUCCESS'),
('APR-2029', 'CITIGROUP INC', 6525475.40, 1766713293.98, 'SPECULATIVE', 'SUCCESS');
GO

-- Formatação Bloomberg Terminal Style
SELECT 
    PERIOD AS [STRATEGIC PERIOD],
    BANK_ENTITY AS [MARKET INSTITUTION],
    FORMAT(PROJECTED_REVENUE_USD, 'C', 'en-US') AS [REVENUE],
    FORMAT(CUMULATIVE_AUM_USD, 'C', 'en-US') AS [CUMULATIVE AUM],
    CONFIDENCE_MATRIX AS [RISK],
    MISSION_STATUS AS [STATUS]
FROM BLOOMBERG_MASTER_REPORT
ORDER BY CUMULATIVE_AUM_USD ASC;
GO
