-- STARGATE SOVEREIGN ARCHITECTURE
-- VERSION: 1.0.4 (ERROR-SUPPRESSED)
-- ARCHITECT: LAURO SERGIO VASCONCELLOS BECK
-- CLUSTER YIELD: 46%

SET SERVEROUTPUT ON;
SET FEEDBACK OFF;
SET PAGESIZE 50;

PROMPT --- INDIVIDUAL NODE GAIN ANALYSIS ---
SELECT 
    Ticker, 
    Region, 
    Base_Val_2026 AS "START_VAL",
    CAST(Base_Val_2026 * POWER(CAGR_Alpha, 3) * Efficiency_Buff AS DECIMAL(10,2)) AS "PROJ_2029"
FROM Stargate_Projection_2029
ORDER BY Region, 4 DESC;

PROMPT --- CLUSTER AGGREGATE SUMMARY ---
SELECT 
    COUNT(*) AS "NODES",
    SUM(Base_Val_2026) AS "BASE_BN",
    CAST(SUM(Base_Val_2026 * POWER(CAGR_Alpha, 3) * Efficiency_Buff) AS DECIMAL(10,2)) AS "PROJ_BN",
    CAST(SUM(Base_Val_2026 * (POWER(CAGR_Alpha, 3) * Efficiency_Buff - 1)) AS DECIMAL(10,2)) AS "ALPHA_GAIN",
    CAST((SUM(Base_Val_2026 * POWER(CAGR_Alpha, 3) * Efficiency_Buff) / SUM(Base_Val_2026) - 1) * 100 AS DECIMAL(5,2)) AS "YIELD_PCT"
FROM Stargate_Projection_2029;
