-- Adding Tickers for BNY, JPM and NEE to avoid ORA-01400
BEGIN
  INSERT INTO CAR_TELEMETRY (BRAND_NAME, TICKER, REBOUND_FACTOR) VALUES ('BNY Mellon', 'BK', 1.42);
  INSERT INTO CAR_TELEMETRY (BRAND_NAME, TICKER, REBOUND_FACTOR) VALUES ('JP Morgan', 'JPM', 1.35);
  UPDATE CAR_TELEMETRY SET REBOUND_FACTOR = 1.48 WHERE BRAND_NAME = 'NextEra Energy';
  COMMIT;
END;
/
