SET ECHO OFF
SET FEEDBACK OFF
SET TERMOUT OFF
SPOOL stargate_infrastructure.sql

PROMPT -- STARGATE INFRASTRUCTURE: PHYSICAL LAYER REBUILD
PROMPT -- DATE: APRIL 27, 2026

PROMPT BEGIN
PROMPT    EXECUTE IMMEDIATE 'DROP TABLE Stargate_Source';
PROMPT EXCEPTION
PROMPT    WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
PROMPT END;
PROMPT /

PROMPT CREATE TABLE Stargate_Source (
PROMPT     Ticker          VARCHAR2(10) PRIMARY KEY,
PROMPT     Q1_26_REV_BN    NUMBER(12,4),
PROMPT     Sector          VARCHAR2(50),
PROMPT     Is_Quantum      NUMBER(1) DEFAULT 0,
PROMPT     Last_Update     TIMESTAMP DEFAULT CURRENT_TIMESTAMP
PROMPT );

PROMPT INSERT INTO Stargate_Source (Ticker, Q1_26_REV_BN, Sector, Is_Quantum)
PROMPT VALUES ('INTC', 13.60, 'TECH_SEMIS', 1);

PROMPT COMMIT;

SPOOL OFF
SET TERMOUT ON
PROMPT [SUCCESS] stargate_infrastructure1.sql created.
