-- STARGATE PROJECT: INFRASTRUCTURE & SECURITY SETUP
-- ARCHITECT: Lauro Sergio Vasconcellos Beck

-- 1. Setup do Novo Schema
ALTER SESSION SET CURRENT_SCHEMA = STARGATE_ADMIN;

-- 2. Master Assets (Big Tech & Oil)
CREATE TABLE ST_MARKET_ASSETS (
    ticker VARCHAR2(10) PRIMARY KEY,
    company_name VARCHAR2(100) NOT NULL,
    sector VARCHAR2(50),
    market_cap_bn NUMBER(15, 2)
);

INSERT INTO ST_MARKET_ASSETS VALUES ('MSFT', 'Microsoft Corp', 'InfoTech', 3150.20);
INSERT INTO ST_MARKET_ASSETS VALUES ('NVDA', 'NVIDIA Corp', 'InfoTech', 2200.00);
INSERT INTO ST_MARKET_ASSETS VALUES ('GOOGL', 'Alphabet Inc', 'BigTech', 2100.50);
INSERT INTO ST_MARKET_ASSETS VALUES ('AMZN', 'Amazon.com Inc', 'Cloud', 1950.80);
INSERT INTO ST_MARKET_ASSETS VALUES ('XOM', 'Exxon Mobil Corp', 'Energy', 450.20);

-- 3. Consulting Matrix (Identity Automation)
CREATE TABLE ST_CONSULTING_MATRIX (
    partnership_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_ticker VARCHAR2(10) REFERENCES ST_MARKET_ASSETS(ticker),
    partner_name VARCHAR2(50),
    engagement_type VARCHAR2(20) CHECK (engagement_type IN ('INNER', 'OUT'))
);

INSERT INTO ST_CONSULTING_MATRIX (client_ticker, partner_name, engagement_type) VALUES ('MSFT', 'Avanade', 'INNER');
INSERT INTO ST_CONSULTING_MATRIX (client_ticker, partner_name, engagement_type) VALUES ('MSFT', 'Accenture', 'INNER');
INSERT INTO ST_CONSULTING_MATRIX (client_ticker, partner_name, engagement_type) VALUES ('NVDA', 'Accenture', 'INNER');
INSERT INTO ST_CONSULTING_MATRIX (client_ticker, partner_name, engagement_type) VALUES ('GOOGL', 'Oracle Services', 'INNER');
INSERT INTO ST_CONSULTING_MATRIX (client_ticker, partner_name, engagement_type) VALUES ('AMZN', 'Accenture', 'INNER');

-- 4. US Banks AI Adoption Telemetry
CREATE TABLE STARGATE_US_BANK_GAINS (
    bank_name VARCHAR2(100),
    implementation_phase VARCHAR2(50),
    partner_lead VARCHAR2(50),
    tech_stack VARCHAR2(100),
    adoption_year NUMBER(4)
);

INSERT INTO STARGATE_US_BANK_GAINS VALUES ('JPMorgan Chase', 'Phase 4: Optimization', 'Accenture', 'Oracle Cloud & AI Services', 2026);
INSERT INTO STARGATE_US_BANK_GAINS VALUES ('Bank of America', 'Phase 3: Deployment', 'Avanade', 'Azure OpenAI & Microsoft Stack', 2026);
INSERT INTO STARGATE_US_BANK_GAINS VALUES ('Goldman Sachs', 'Phase 2: Migration', 'Accenture', 'Oracle Database@Azure', 2025);
INSERT INTO STARGATE_US_BANK_GAINS VALUES ('Citigroup', 'Phase 1: Pilot', 'Accenture', 'Legacy Oracle Modernization', 2027);

COMMIT;
