-- AUTHOR: LAURO BECK (SENIOR ENTERPRISE ARCHITECT)
-- PROJECT: STARGATE CLUSTER v15.5
UPDATE SYS.STARGATE_REVENUE_BASE 
SET status_mission = 'MISSION_SUCCESS',
    partner_lead = 'Lauro Sergio V. Beck',
    last_update = SYSDATE;

COMMIT;

PROMPT [MISSION_SUCCESS] WRITTEN TO SYS.STARGATE_REVENUE_BASE
